package io.appwrite.enums

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Flag(val value: String) {
    @SerialName("af")
    AFGHANISTAN("af"),
    @SerialName("ao")
    ANGOLA("ao"),
    @SerialName("al")
    ALBANIA("al"),
    @SerialName("ad")
    ANDORRA("ad"),
    @SerialName("ae")
    UNITED_ARAB_EMIRATES("ae"),
    @SerialName("ar")
    ARGENTINA("ar"),
    @SerialName("am")
    ARMENIA("am"),
    @SerialName("ag")
    ANTIGUA_AND_BARBUDA("ag"),
    @SerialName("au")
    AUSTRALIA("au"),
    @SerialName("at")
    AUSTRIA("at"),
    @SerialName("az")
    AZERBAIJAN("az"),
    @SerialName("bi")
    BURUNDI("bi"),
    @SerialName("be")
    BELGIUM("be"),
    @SerialName("bj")
    BENIN("bj"),
    @SerialName("bf")
    BURKINA_FASO("bf"),
    @SerialName("bd")
    BANGLADESH("bd"),
    @SerialName("bg")
    BULGARIA("bg"),
    @SerialName("bh")
    BAHRAIN("bh"),
    @SerialName("bs")
    BAHAMAS("bs"),
    @SerialName("ba")
    BOSNIA_AND_HERZEGOVINA("ba"),
    @SerialName("by")
    BELARUS("by"),
    @SerialName("bz")
    BELIZE("bz"),
    @SerialName("bo")
    BOLIVIA("bo"),
    @SerialName("br")
    BRAZIL("br"),
    @SerialName("bb")
    BARBADOS("bb"),
    @SerialName("bn")
    BRUNEI_DARUSSALAM("bn"),
    @SerialName("bt")
    BHUTAN("bt"),
    @SerialName("bw")
    BOTSWANA("bw"),
    @SerialName("cf")
    CENTRAL_AFRICAN_REPUBLIC("cf"),
    @SerialName("ca")
    CANADA("ca"),
    @SerialName("ch")
    SWITZERLAND("ch"),
    @SerialName("cl")
    CHILE("cl"),
    @SerialName("cn")
    CHINA("cn"),
    @SerialName("ci")
    COTE_DIVOIRE("ci"),
    @SerialName("cm")
    CAMEROON("cm"),
    @SerialName("cd")
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("cd"),
    @SerialName("cg")
    REPUBLIC_OF_THE_CONGO("cg"),
    @SerialName("co")
    COLOMBIA("co"),
    @SerialName("km")
    COMOROS("km"),
    @SerialName("cv")
    CAPE_VERDE("cv"),
    @SerialName("cr")
    COSTA_RICA("cr"),
    @SerialName("cu")
    CUBA("cu"),
    @SerialName("cy")
    CYPRUS("cy"),
    @SerialName("cz")
    CZECH_REPUBLIC("cz"),
    @SerialName("de")
    GERMANY("de"),
    @SerialName("dj")
    DJIBOUTI("dj"),
    @SerialName("dm")
    DOMINICA("dm"),
    @SerialName("dk")
    DENMARK("dk"),
    @SerialName("do")
    DOMINICAN_REPUBLIC("do"),
    @SerialName("dz")
    ALGERIA("dz"),
    @SerialName("ec")
    ECUADOR("ec"),
    @SerialName("eg")
    EGYPT("eg"),
    @SerialName("er")
    ERITREA("er"),
    @SerialName("es")
    SPAIN("es"),
    @SerialName("ee")
    ESTONIA("ee"),
    @SerialName("et")
    ETHIOPIA("et"),
    @SerialName("fi")
    FINLAND("fi"),
    @SerialName("fj")
    FIJI("fj"),
    @SerialName("fr")
    FRANCE("fr"),
    @SerialName("fm")
    MICRONESIA_FEDERATED_STATES_OF("fm"),
    @SerialName("ga")
    GABON("ga"),
    @SerialName("gb")
    UNITED_KINGDOM("gb"),
    @SerialName("ge")
    GEORGIA("ge"),
    @SerialName("gh")
    GHANA("gh"),
    @SerialName("gn")
    GUINEA("gn"),
    @SerialName("gm")
    GAMBIA("gm"),
    @SerialName("gw")
    GUINEA_BISSAU("gw"),
    @SerialName("gq")
    EQUATORIAL_GUINEA("gq"),
    @SerialName("gr")
    GREECE("gr"),
    @SerialName("gd")
    GRENADA("gd"),
    @SerialName("gt")
    GUATEMALA("gt"),
    @SerialName("gy")
    GUYANA("gy"),
    @SerialName("hn")
    HONDURAS("hn"),
    @SerialName("hr")
    CROATIA("hr"),
    @SerialName("ht")
    HAITI("ht"),
    @SerialName("hu")
    HUNGARY("hu"),
    @SerialName("id")
    INDONESIA("id"),
    @SerialName("in")
    INDIA("in"),
    @SerialName("ie")
    IRELAND("ie"),
    @SerialName("ir")
    IRAN_ISLAMIC_REPUBLIC_OF("ir"),
    @SerialName("iq")
    IRAQ("iq"),
    @SerialName("is")
    ICELAND("is"),
    @SerialName("il")
    ISRAEL("il"),
    @SerialName("it")
    ITALY("it"),
    @SerialName("jm")
    JAMAICA("jm"),
    @SerialName("jo")
    JORDAN("jo"),
    @SerialName("jp")
    JAPAN("jp"),
    @SerialName("kz")
    KAZAKHSTAN("kz"),
    @SerialName("ke")
    KENYA("ke"),
    @SerialName("kg")
    KYRGYZSTAN("kg"),
    @SerialName("kh")
    CAMBODIA("kh"),
    @SerialName("ki")
    KIRIBATI("ki"),
    @SerialName("kn")
    SAINT_KITTS_AND_NEVIS("kn"),
    @SerialName("kr")
    SOUTH_KOREA("kr"),
    @SerialName("kw")
    KUWAIT("kw"),
    @SerialName("la")
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("la"),
    @SerialName("lb")
    LEBANON("lb"),
    @SerialName("lr")
    LIBERIA("lr"),
    @SerialName("ly")
    LIBYA("ly"),
    @SerialName("lc")
    SAINT_LUCIA("lc"),
    @SerialName("li")
    LIECHTENSTEIN("li"),
    @SerialName("lk")
    SRI_LANKA("lk"),
    @SerialName("ls")
    LESOTHO("ls"),
    @SerialName("lt")
    LITHUANIA("lt"),
    @SerialName("lu")
    LUXEMBOURG("lu"),
    @SerialName("lv")
    LATVIA("lv"),
    @SerialName("ma")
    MOROCCO("ma"),
    @SerialName("mc")
    MONACO("mc"),
    @SerialName("md")
    MOLDOVA("md"),
    @SerialName("mg")
    MADAGASCAR("mg"),
    @SerialName("mv")
    MALDIVES("mv"),
    @SerialName("mx")
    MEXICO("mx"),
    @SerialName("mh")
    MARSHALL_ISLANDS("mh"),
    @SerialName("mk")
    NORTH_MACEDONIA("mk"),
    @SerialName("ml")
    MALI("ml"),
    @SerialName("mt")
    MALTA("mt"),
    @SerialName("mm")
    MYANMAR("mm"),
    @SerialName("me")
    MONTENEGRO("me"),
    @SerialName("mn")
    MONGOLIA("mn"),
    @SerialName("mz")
    MOZAMBIQUE("mz"),
    @SerialName("mr")
    MAURITANIA("mr"),
    @SerialName("mu")
    MAURITIUS("mu"),
    @SerialName("mw")
    MALAWI("mw"),
    @SerialName("my")
    MALAYSIA("my"),
    @SerialName("na")
    NAMIBIA("na"),
    @SerialName("ne")
    NIGER("ne"),
    @SerialName("ng")
    NIGERIA("ng"),
    @SerialName("ni")
    NICARAGUA("ni"),
    @SerialName("nl")
    NETHERLANDS("nl"),
    @SerialName("no")
    NORWAY("no"),
    @SerialName("np")
    NEPAL("np"),
    @SerialName("nr")
    NAURU("nr"),
    @SerialName("nz")
    NEW_ZEALAND("nz"),
    @SerialName("om")
    OMAN("om"),
    @SerialName("pk")
    PAKISTAN("pk"),
    @SerialName("pa")
    PANAMA("pa"),
    @SerialName("pe")
    PERU("pe"),
    @SerialName("ph")
    PHILIPPINES("ph"),
    @SerialName("pw")
    PALAU("pw"),
    @SerialName("pg")
    PAPUA_NEW_GUINEA("pg"),
    @SerialName("pl")
    POLAND("pl"),
    @SerialName("pf")
    FRENCH_POLYNESIA("pf"),
    @SerialName("kp")
    NORTH_KOREA("kp"),
    @SerialName("pt")
    PORTUGAL("pt"),
    @SerialName("py")
    PARAGUAY("py"),
    @SerialName("qa")
    QATAR("qa"),
    @SerialName("ro")
    ROMANIA("ro"),
    @SerialName("ru")
    RUSSIA("ru"),
    @SerialName("rw")
    RWANDA("rw"),
    @SerialName("sa")
    SAUDI_ARABIA("sa"),
    @SerialName("sd")
    SUDAN("sd"),
    @SerialName("sn")
    SENEGAL("sn"),
    @SerialName("sg")
    SINGAPORE("sg"),
    @SerialName("sb")
    SOLOMON_ISLANDS("sb"),
    @SerialName("sl")
    SIERRA_LEONE("sl"),
    @SerialName("sv")
    EL_SALVADOR("sv"),
    @SerialName("sm")
    SAN_MARINO("sm"),
    @SerialName("so")
    SOMALIA("so"),
    @SerialName("rs")
    SERBIA("rs"),
    @SerialName("ss")
    SOUTH_SUDAN("ss"),
    @SerialName("st")
    SAO_TOME_AND_PRINCIPE("st"),
    @SerialName("sr")
    SURINAME("sr"),
    @SerialName("sk")
    SLOVAKIA("sk"),
    @SerialName("si")
    SLOVENIA("si"),
    @SerialName("se")
    SWEDEN("se"),
    @SerialName("sz")
    ESWATINI("sz"),
    @SerialName("sc")
    SEYCHELLES("sc"),
    @SerialName("sy")
    SYRIA("sy"),
    @SerialName("td")
    CHAD("td"),
    @SerialName("tg")
    TOGO("tg"),
    @SerialName("th")
    THAILAND("th"),
    @SerialName("tj")
    TAJIKISTAN("tj"),
    @SerialName("tm")
    TURKMENISTAN("tm"),
    @SerialName("tl")
    TIMOR_LESTE("tl"),
    @SerialName("to")
    TONGA("to"),
    @SerialName("tt")
    TRINIDAD_AND_TOBAGO("tt"),
    @SerialName("tn")
    TUNISIA("tn"),
    @SerialName("tr")
    TURKEY("tr"),
    @SerialName("tv")
    TUVALU("tv"),
    @SerialName("tz")
    TANZANIA("tz"),
    @SerialName("ug")
    UGANDA("ug"),
    @SerialName("ua")
    UKRAINE("ua"),
    @SerialName("uy")
    URUGUAY("uy"),
    @SerialName("us")
    UNITED_STATES("us"),
    @SerialName("uz")
    UZBEKISTAN("uz"),
    @SerialName("va")
    VATICAN_CITY("va"),
    @SerialName("vc")
    SAINT_VINCENT_AND_THE_GRENADINES("vc"),
    @SerialName("ve")
    VENEZUELA("ve"),
    @SerialName("vn")
    VIETNAM("vn"),
    @SerialName("vu")
    VANUATU("vu"),
    @SerialName("ws")
    SAMOA("ws"),
    @SerialName("ye")
    YEMEN("ye"),
    @SerialName("za")
    SOUTH_AFRICA("za"),
    @SerialName("zm")
    ZAMBIA("zm"),
    @SerialName("zw")
    ZIMBABWE("zw");

    override fun toString() = value
}