name: Build and Publish to Maven Central

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'Release version (e.g., v0.2.1 or 0.2.1)'
        required: true
        default: '0.2.1'

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    env:
      RAW_VERSION: ${{ 
        SDK_VERSION=$(echo "${{ env.RAW_VERSION }}" | sed -E 's/.*([0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9._]+)?)$/\1/')
        }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Process version
        run: |
          SDK_VERSION=$(echo "${{ env.RAW_VERSION }}" | sed -E 's/.*?([0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9._]+)?)$/\1/')
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
      - name: Set Gradle version
        run: echo "version=${{ env.SDK_VERSION }}" >> gradle.properties
      - name: Publish to MavenCentral
        run: ./gradlew publishToMavenCentral  --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
